### ISSUE TITLE
Availability to change separator

### ISSUE THREAD

**Issue by lneninger** [georapbox/webStorage.js#2]
I want to be able to change the separator string:

<prefix><separator><keyname>

I saw that the fixed one is "/" and I want to change it.

**Comment by georapbox** [comment]
As of version 2.1.0 you can now configure the separator using the `keySeparator` option when creating a new instance.

Example:
```js
var myWebStorage = webStorage.createInstance({
  name: 'myDB',
  keySeparator: '-'
});
```
